class PersonalData {
  static Map<String, String> data = {
    "First Name": "Andy X1 PM",
    "Last Name": "",
    "Display Name": "Andy X1 PM",
    "Nickname": "",
    "E-mail Address": "",
    "E-mail 2 Address": "",
    "E-mail 3 Address": "",
    "Home Phone": "",
    "Business Phone": "",
    "Home Fax": "",
    "Business Fax": "",
    "Pager": "",
    "Mobile Phone": "085-641-344149",
    "Home Street": "",
    "Home Address 2": "",
    "Home City": "",
    "Home State": "",
    "Home Postal Code": "",
    "Home Country": "",
    "Business Address": "",
    "Business Address 2": "",
    "Business City": "",
    "Business State": "",
    "Business Postal Code": "",
    "Business Country": "",
    "Country Code": "",
    "Related name": "",
    "Job Title": "",
    "Department": "",
    "Organization": "",
    "Notes": "",
    "Birthday": "",
    "Anniversary": "",
    "Gender": "",
    "Web Page": "",
    "Web Page 2": "",
    "Categories": ""
  };
}
